<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <SkipRefsCheck>true</SkipRefsCheck>
  </PropertyGroup>
  <ItemGroup>
    <Reference Remove="@(Reference)" />
    <Compile Include="../../examples/ReskinPack/ReskinMod.cs" Link="ReskinMod.cs" />
    <Compile Include="../../src/KingdomMod.Api/PackApi.cs" Link="PackApi.cs" />
  </ItemGroup>
</Project>
